name: Dependency Scan

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 0 * * 0' # Run weekly

jobs:
  dependency-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r app/requirements.txt
      - name: Run Dependabot
        uses: dependabot/fetch-metadata@v2
      - name: Scan for vulnerabilities
        run: |
          pip install safety
          safety check -r backend/app/requirements.txt